CREATE TABLE IF NOT EXISTS oauth_clients (client_id text PRIMARY KEY, client_name text NOT NULL, redirect_uris jsonb NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS users (id uuid PRIMARY KEY, display_name text, email text, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS oauth_identities (provider text NOT NULL, provider_subject text NOT NULL, user_id uuid NOT NULL REFERENCES users(id), PRIMARY KEY(provider,provider_subject));
CREATE TABLE IF NOT EXISTS oauth_login_states (id uuid PRIMARY KEY, client_id text NOT NULL REFERENCES oauth_clients(client_id), redirect_uri text NOT NULL, oauth_state text NOT NULL, code_challenge text NOT NULL, resource text NOT NULL, scope text NOT NULL, expires_at timestamptz NOT NULL);
CREATE TABLE IF NOT EXISTS oauth_codes (code_hash text PRIMARY KEY, user_id uuid NOT NULL REFERENCES users(id), client_id text NOT NULL REFERENCES oauth_clients(client_id), redirect_uri text NOT NULL, code_challenge text NOT NULL, resource text NOT NULL, scope text NOT NULL, expires_at timestamptz NOT NULL);
CREATE TABLE IF NOT EXISTS oauth_pending_consents (token_hash text PRIMARY KEY, user_id uuid NOT NULL REFERENCES users(id), client_id text NOT NULL REFERENCES oauth_clients(client_id), redirect_uri text NOT NULL, oauth_state text NOT NULL, code_challenge text NOT NULL, resource text NOT NULL, scope text NOT NULL, expires_at timestamptz NOT NULL);
CREATE TABLE IF NOT EXISTS refresh_tokens (token_hash text PRIMARY KEY, user_id uuid NOT NULL REFERENCES users(id), client_id text NOT NULL REFERENCES oauth_clients(client_id), scope text NOT NULL, expires_at timestamptz NOT NULL, revoked_at timestamptz);
CREATE TABLE IF NOT EXISTS wallets (user_id uuid PRIMARY KEY REFERENCES users(id), cdp_account_name text NOT NULL UNIQUE, address text, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS payment_previews (id uuid PRIMARY KEY, user_id uuid NOT NULL REFERENCES users(id), method text NOT NULL, url text NOT NULL, request_body jsonb, fingerprint text NOT NULL, amount numeric(78,0) NOT NULL, pay_to text NOT NULL, expires_at timestamptz NOT NULL, used_at timestamptz);
CREATE TABLE IF NOT EXISTS payments (id uuid PRIMARY KEY, user_id uuid NOT NULL REFERENCES users(id), preview_id uuid NOT NULL UNIQUE REFERENCES payment_previews(id), amount numeric(78,0) NOT NULL, purpose text NOT NULL, status text NOT NULL CHECK(status IN ('reserved','settled','failed','unknown')), transaction_hash text, response_status integer, error text, created_at timestamptz NOT NULL DEFAULT now(), completed_at timestamptz);
ALTER TABLE payments ADD COLUMN IF NOT EXISTS purpose text;
UPDATE payments SET purpose='legacy payment' WHERE purpose IS NULL;
ALTER TABLE payments ALTER COLUMN purpose SET NOT NULL;
CREATE INDEX IF NOT EXISTS payments_user_window ON payments(user_id,created_at DESC);
ALTER TABLE oauth_login_states ADD COLUMN IF NOT EXISTS browser_session_hash text;
ALTER TABLE oauth_login_states ADD COLUMN IF NOT EXISTS csrf_token_hash text;
ALTER TABLE oauth_login_states ADD COLUMN IF NOT EXISTS approved_at timestamptz;
ALTER TABLE oauth_login_states ADD COLUMN IF NOT EXISTS provider text;
ALTER TABLE oauth_pending_consents ADD COLUMN IF NOT EXISTS approved_at timestamptz;
ALTER TABLE oauth_clients ADD COLUMN IF NOT EXISTS last_used_at timestamptz;
CREATE TABLE IF NOT EXISTS oauth_rate_limits (bucket text NOT NULL, subject_hash text NOT NULL, window_start timestamptz NOT NULL, request_count integer NOT NULL, PRIMARY KEY(bucket,subject_hash));
ALTER TABLE refresh_tokens ADD COLUMN IF NOT EXISTS family_id text;
ALTER TABLE refresh_tokens ADD COLUMN IF NOT EXISTS used_at timestamptz;
UPDATE refresh_tokens SET family_id=token_hash WHERE family_id IS NULL;
ALTER TABLE refresh_tokens ALTER COLUMN family_id SET NOT NULL;
CREATE INDEX IF NOT EXISTS refresh_tokens_family ON refresh_tokens(family_id);
